### ISSUE TITLE
Provide a means of recovering (or prevention) if the passphrase fails after checking all the keys

### ISSUE THREAD

**Issue by pastcompute** [frasertweedale/gcaff#5]
Hi,

I got all the way through checking keys and hit the sign button, then got an error MISSING PASSPHRASE.

I don't know why this happened, because I I had gpg-agent running. Perhaps I accidentally ran gcaff from a terminal window started prior to gpg-agent. Anyhow.

I copied and pasted part of the log (I had logging=DEBUG) so after some sleep I might try and hack something together to parse the output of 'DEBUG:gcaff.ui:sign and send' and try again.

On reflection I havent yet setup my second private key into my gpg-agent script so maybe that caused it.

Anyway, I think it might be useful, rather than exiting, to either give a chance to respawn gpg-agent (will that work? or is it too late?) or do a test that the (all) private keys are accessible before starting ?

**Comment by frasertweedale** [comment]
Oh yeah, this is an important one.  I will do this work.  Got some long-haul flights coming up in the next few weeks, so I might tackle it then.

**Comment by pastcompute** [comment]
Just a bit more info.
I suspect what happened is this:
- I have two keys
- I didn't unlock the second key into gpg-agent
- `gcaff` detected the presence of gpg-agent OK when it tests for it
- `gcaff` scans for the signing keys to choose from using the `gpg` program
- `gcaff` doesn't test that all selected keys are usable via `gpg-agent`

Looking at the code, I'd guess you could add a test in `on_signing_keys_changed()` in `ui.py`

If the user subsequently terminates `gpg-agent` its their own problem thereafter...

**Comment by pastcompute** [comment]
For the benefit of others having the same issue, copy the log report starting with `DEBUG:gcaff.ui:sign and send:` which is a massive Python tuple array thing and do something like:

```
x=<pasted stuff, started with [ and ends with ]>
for i in range(0,len(x)) : print x[i][1][3], x[i][0][3], x[i][0][2], x[i][1][4]
```

and this will give you a list that is in the order of what you previously did to make it easier to find

**Comment by pastcompute** [comment]
Here are some more logs:

```
INFO:gcaff.gpg:execute gpg: GNUPGHOME=/tmp/tmpkVXYPb ['gpg', '--no-tty', '--use-agent', '--no-auto-check-trustdb', '--secret-keyring', '/home/me/.gnupg/secring.gpg', '--command-fd', '0', '--status-fd', '1', '--default-cert-level', '2', '--no-ask-cert-level', '--cert-digest-algo', 'SHA256', '--local-user', '<KEYREDACTED>', '--edit-key', '<REDACTED>']
DEBUG:gcaff.gpg:[GNUPG:] GET_LINE keyedit.prompt
DEBUG:gcaff.gpg:minimize
DEBUG:gcaff.gpg:[GNUPG:] GOT_IT
DEBUG:gcaff.gpg:[GNUPG:] GET_LINE keyedit.prompt
DEBUG:gcaff.gpg:1
DEBUG:gcaff.gpg:[GNUPG:] GOT_IT
DEBUG:gcaff.gpg:[GNUPG:] GET_LINE keyedit.prompt
DEBUG:gcaff.gpg:sign
DEBUG:gcaff.gpg:[GNUPG:] GOT_IT
DEBUG:gcaff.gpg:[GNUPG:] GET_BOOL sign_uid.okay
DEBUG:gcaff.gpg:y
DEBUG:gcaff.gpg:[GNUPG:] GOT_IT
DEBUG:gcaff.gpg:[GNUPG:] USERID_HINT <KEYREDACTED> <<UIDREDACTED>>
DEBUG:gcaff.gpg:ignore unrecognised message: 'USERID_HINT <KEYREDACTED> <<UIDREDACTED>>'
DEBUG:gcaff.gpg:[GNUPG:] NEED_PASSPHRASE <KEYREDACTED> <KEYREDACTED> 1 0
DEBUG:gcaff.gpg:ignore unrecognised message: 'NEED_PASSPHRASE <KEYREDACTED> <KEYREDACTED> 1 0'
DEBUG:gcaff.gpg:[GNUPG:] MISSING_PASSPHRASE
DEBUG:gcaff.gpg:[GNUPG:] BAD_PASSPHRASE <KEYREDACTED>
DEBUG:gcaff.gpg:[GNUPG:] GET_LINE keyedit.prompt
DEBUG:gcaff.gpg:quit
DEBUG:gcaff.gpg:[GNUPG:] GOT_IT
DEBUG:gcaff.gpg:
DEBUG:gcaff.gpg:ignore unrecognised message: ''
INFO:gcaff.gpg:gpg process exited code 2
WARNING:root:remove tmpgpgdir: /tmp/tmpkVXYPb
```

**Comment by pastcompute** [comment]
Alright, this seems to be a deeper problem. I triple checked I am running `gpg-agent` and sourced the -gpg file so I have a valid `GPG_AGENT_INFO` environment variable, but it still fails.
So I manually stepped through the process using a dummy key in my home directory.

When running

```
gpg  --use-agent --no-auto-check-trustdb --secret-keyring /home/me/.gnupg/secring.gpg --command-fd 0 --status-fd 1 --default-cert-level 2 --no-ask-cert-level --cert-digest-algo SHA256 --local-user <SIGNINGKEY>--edit-key <KEY2>
```

gpg-agent pops up asking for the passphrase, in spite of the fact I previously entered the passphrase before starting.

So I am starting to suspect there is a problem with how I am using gpg-agent, or something, rather than a bug in gcaff.
However, checking that the signing key was previously opened by gpg-agent is probably still a useful feature.

**Comment by pastcompute** [comment]
Again for the benefit of others:
- Upgraded to gpg2 - still asks me for passphrase even though I already unlocked it
- Upgraded to latest wheezy versions of everything - still asks me for passphrase even though I already unlocked it

So one thing I noticed now.
When keychain starts, the passphrase message looks like this:

```
┌───────────────────────────────────────────────────────────────────────────┐
│ You need a passphrase to unlock the secret key for user:                  │
│ "blah@blah"                                                               │
│ 4096-bit RSA key, ID xxxxxxxx, created 2015-01-09 (main key ID yyyyyyyy)  │
│                                                                           │
│                                                                           │
│ Passphrase ______________________________________________________________ │
│                                                                           │
│           <OK>                                           <Cancel>         │
└───────────────────────────────────────────────────────────────────────────┘
```

The prompt used when invoked via gcaff's gpg command call is

```
┌────────────────────────────────────────────────────────────┐
│ You need a passphrase to unlock the secret key for user:   │
│ "blah@blah"                                                               │
│ 4096-bit RSA key, ID yyyyyyyy, created 2015-01-09  │
│                                                            │
│                                                            │
│ Passphrase _______________________________________________ │
│                                                            │
│        <OK>                                  <Cancel>      │
└────────────────────────────────────────────────────────────┘
```

GPG2 is similar but uses the word passphrase.

So I am wondering if for some reason keychain is only opening a subkey or something and the signing process used by gcaff is opening the entire key?

**Comment by pastcompute** [comment]
So I thought a good workaround would be to cause `gpg-agent` to open the key by signing a dummy key then running `gcaff` ...

Now I have something called `pinentry` spinning a core at 100% and `gcaff` frozen, so that didn't work.

So annoyingly I will have to fallback to the original caff program.

Other info that may be relevant:

gpg2 2.0.19
gpg-agent 2.0.19
Debian Wheezy amd64

**Comment by frasertweedale** [comment]
Sounds like something funky is up with your `gpg-agent` and `pinentry` setup.  The normal behaviour for GnuPG 2.0 is for GnuPG to ask `gpg-agent` to unlock a key, and for `gpg-agent` to invoke a `pinentry` program to prompt the user for their passphrase.

FWIW, recent versions of GnuPG and `gpg-agent` have a `use-standard-socket` open where the agent listens on a well known socket in `$GNUPGHOME/S.gpg-agent` and `gpg` tries to connect there, so you may be able to dispense with the `GPG_AGENT_INFO` envvar and avoid sourcing the file.  This would at least narrow down the number of things that need to be controlled in figuring out this issue.

I will try with the same programs on Debian Wheezy (7.8) on the weekend and see if I can reproduce the behaviour you are seeing.

**Comment by pastcompute** [comment]
Thanks. Its not urgent, I managed to get it done using just caff. I use openbox which probably misses something important. I've actually noticed pinentry at 100% CPU before, usually some houra after logging in where I havent had a need to unlock a key yet and the shell script terminal is just minimised in the background. So wrt gcaff I dont think there is anything that can be done, other than the check for failure to unlock a key before embarking on checking all the ids.

**Comment by frasertweedale** [comment]
OK, well I will force key unlock before uid selection begins.  I suppose that _somewhat_ obviates the original request, i.e., recover/resume when signing fails _after_ uids have been chosen.

It's still possible to fail afterwards, but far less likely :)
